version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-document-manager}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - document-manager
      - default
    restart: unless-stopped

  minio:
    container_name: minio_container
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    hostname: minio1
    volumes:
      - minio:/export
    ports:
      - "9000:9000"
    networks:
      - document-manager
      - default
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    command: server /export
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - document-manager
      - default
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0

networks:
  document-manager:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  pg_storage:
  minio:
