POST http://localhost:8080/api/search
Content-Type: application/json

{
  "query": "some"
}

###

POST http://localhost:8080/api/search
Content-Type: application/json

{
  "query": "some",
  "filter": {
    "term": {
      "assets.metadata.access_permission:can_print": "true"
    }
  }
}

###

POST http://localhost:8080/api/search
Content-Type: application/json

{
  "query": "some",
  "sort": [
    {
      "field": "title",
      "order": "DESC"
    }
  ]
}

###
