name: Release-build

on:
  release:
    types: [created]

jobs:
  build-uber-jar:
    name: Build uber-jar for standalone
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify -Dquarkus.package.type=uber-jar
      - name: Upload uber-jar
        id: upload-uber-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/document-manager-${{ github.event.release.tag_name }}-runner.jar
          asset_name: document-manager-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/octet-stream

  build-native:
    name: Build and test native linux executable
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '21.1.0.java11'
      - name: Install native-image
        run: gu install native-image
      - name: Set version
        run: ./mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
      - name: Build native executable
        run: ./mvnw package -Pnative
      - name: Upload native executable
        id: upload-native-executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/document-manager-${{ github.event.release.tag_name }}-runner
          asset_name: document-manager-${{ github.event.release.tag_name }}-linux
          asset_content_type: application/octet-stream
      - name: Upload native-executable for Docker Build
        id: upload-native-executable-for-docker
        uses: actions/upload-artifact@master
        with:
          name: document-manager-runner
          path: ./target/document-manager-${{ github.event.release.tag_name }}-runner

  push_to_registry:
    name: Push Docker image to Github Packages
    needs: build-native
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download built artifact
        uses: actions/download-artifact@master
        with:
          name: document-manager-runner
          path: ./target/document-manager-runner
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/document-manager/documentor:latest
            ghcr.io/document-manager/documentor:${{ github.event.release.tag_name }}
