name: Release-build

on:
  release:
    types: [created]

jobs:
  build-uber-jar:
    name: Build uber-jar for standalone
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify -Dquarkus.package.type=uber-jar
      - name: Upload uber-jar
        id: upload-uber-jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/documentor-${{ github.event.release.tag_name }}-runner.jar
          asset_name: documentor-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/octet-stream

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set version
        run: ./mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
      - name: Build jar
        run: ./mvnw clean package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/document-manager/documentor:latest
            ghcr.io/document-manager/documentor:${{ github.event.release.tag_name }}
